### PR TITLE
[TECH-1397] Config port

### PR DESCRIPTION
**Pull request by pmcnr-hx**
#### What does this PR do? (please provide any background)

It allows configuring the MySQL server port.
#### What tests does this PR have?

N/A
#### How can this be tested?

Attempt to connect to a MySQL server database on a non-standard (other than `3306`) port.
#### Screenshots / Screencast

N/A
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.
#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.
#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by tompricetech** [comment]
Taking Dev

**Comment by tompricetech** [comment]
Seen this working on devd :+1:

**Comment by andycastleuk** [comment]
Got SE.

**Comment by andycastleuk** [comment]
Looks good :+1: Need to make sure we version tag this correctly when it gets merged :)

**Comment by pmcnr-hx** [comment]
Thanks for the tagging reminder @andrew-c!

**Pull request merged**
