### PR TITLE
TECH-1122 adding a port option to dabase connection configuration

### PR DESCRIPTION
**Pull request by stuartstobie**
#### What does this PR do?

Adds the option to state which port you wish to connect on. This does not mean all projects that currently use this module will need to be updated to specify a port as leaving it blank should result in the use of the default port. 
#### What unit or integration tests does this PR have?

None.
#### What selenium tests does this PR have?

None.
#### How should a developer review this?

Look at the teeny-tiny change and check it seems reasonable. 
#### How should this be manually tested?

Go into the repo
`node test` to run the test, you should see a result.
If you insert `port: 3306,` or `port: undefined`, around line 6 of the test and run it you should see the same result.
#### Any background context you want to provide?

A project I'm working on needs to be able to specify the port it will connect to a database on, nuff said. 
#### What are the relevant tickets?

TECH-1122
#### What gif best describes how you feel about this work?

avenger dogs

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit, selenium and regression test coverage.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this cross-browser/device for visual changes.
- [x] I've checked any significant visual changes with a member of the UX/UI pod.
- [x] I've checked this work against the requirements of the Jira.
- [x] I've manually checked this work against any dependent systems.
- [x] I've added and updated translations for all supported languages.
- [x] I've informed those who need to know of any unforeseen impact of this work (database migrations, deployment procedure changes).
- [x] I've checked that there are no negative speed or performance impacts from my work.
- [x] I've added appropriate tracking.
- [x] I am ready for this to be code reviewed, merged and tested.
- [x] I've thought about writing a blog post about this.
#### IP or Developer Review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] +1 from me!
#### Software Engineer or Developer review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] +1 from me!
#### Software Engineer or project guru review:
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve run all the tests locally and they pass.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!
#### Software Tester review
- [ ] I’ve run all the selenium tests locally and they pass.
- [ ] I agree with the test coverage.
- [ ] I've checked for Ruby changes and understand how to deploy if present.

### CODE REVIEW

**Comment by pmcnr-hx** [comment]
Taking SE/Dev.

**Comment by pmcnr-hx** [comment]
Was it @hxoliverrumbelow that did SE/Guru?

**Comment by pmcnr-hx** [comment]
:+1:

**Comment by hxgeorge** [comment]
Taking IP

**Comment by hxgeorge** [comment]
+1

**Pull request merged**
